package com.whoops.dao;

import com.whoops.po.AuditPost;
import com.whoops.po.AuditPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuditPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int countByExample(AuditPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int deleteByExample(AuditPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int insert(AuditPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int insertSelective(AuditPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    List<AuditPost> selectByExample(AuditPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    AuditPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int updateByExampleSelective(@Param("record") AuditPost record, @Param("example") AuditPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int updateByExample(@Param("record") AuditPost record, @Param("example") AuditPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int updateByPrimaryKeySelective(AuditPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_post
     *
     * @mbggenerated Sun Apr 19 15:36:01 EDT 2015
     */
    int updateByPrimaryKey(AuditPost record);
}