package com.whoops.dao;

import com.whoops.po.FavorPost;
import com.whoops.po.FavorPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavorPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int countByExample(FavorPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int deleteByExample(FavorPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int insert(FavorPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int insertSelective(FavorPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    List<FavorPost> selectByExample(FavorPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    FavorPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int updateByExampleSelective(@Param("record") FavorPost record, @Param("example") FavorPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int updateByExample(@Param("record") FavorPost record, @Param("example") FavorPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int updateByPrimaryKeySelective(FavorPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_post
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    int updateByPrimaryKey(FavorPost record);
}