package com.whoops.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.whoops.po.FavorSchool;
import com.whoops.po.FavorSchoolExample;

public interface FavorSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int countByExample(FavorSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int deleteByExample(FavorSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int insert(FavorSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int insertSelective(FavorSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    List<FavorSchool> selectByExample(FavorSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    FavorSchool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int updateByExampleSelective(@Param("record") FavorSchool record, @Param("example") FavorSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int updateByExample(@Param("record") FavorSchool record, @Param("example") FavorSchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int updateByPrimaryKeySelective(FavorSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_school
     *
     * @mbggenerated Mon Mar 09 17:01:09 EDT 2015
     */
    int updateByPrimaryKey(FavorSchool record);

	List<FavorSchool> selectFavorSchoolByUid(Integer uid);
}