package com.whoops.dao;

import com.whoops.po.ManagerUser;
import com.whoops.po.ManagerUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int countByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int deleteByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int insert(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int insertSelective(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    List<ManagerUser> selectByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    ManagerUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int updateByExampleSelective(@Param("record") ManagerUser record, @Param("example") ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int updateByExample(@Param("record") ManagerUser record, @Param("example") ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int updateByPrimaryKeySelective(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    int updateByPrimaryKey(ManagerUser record);
}