package com.whoops.dao;

import com.whoops.po.LikePost;
import com.whoops.po.LikePostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LikePostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int countByExample(LikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int deleteByExample(LikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int insert(LikePost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int insertSelective(LikePost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    List<LikePost> selectByExample(LikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    LikePost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int updateByExampleSelective(@Param("record") LikePost record, @Param("example") LikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int updateByExample(@Param("record") LikePost record, @Param("example") LikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int updateByPrimaryKeySelective(LikePost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_post
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    int updateByPrimaryKey(LikePost record);
}