package com.whoops.po;

import java.util.Date;

public class LikeComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_comment.id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_comment.uid
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_comment.comment_id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_comment.type
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_comment.create_date
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_comment.id
     *
     * @return the value of like_comment.id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_comment.id
     *
     * @param id the value for like_comment.id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_comment.uid
     *
     * @return the value of like_comment.uid
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_comment.uid
     *
     * @param uid the value for like_comment.uid
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_comment.comment_id
     *
     * @return the value of like_comment.comment_id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_comment.comment_id
     *
     * @param commentId the value for like_comment.comment_id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_comment.type
     *
     * @return the value of like_comment.type
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_comment.type
     *
     * @param type the value for like_comment.type
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_comment.create_date
     *
     * @return the value of like_comment.create_date
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_comment.create_date
     *
     * @param createDate the value for like_comment.create_date
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}