package com.whoops.po;

public class ManagerUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.id
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.username
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.password
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.type
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.status
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.id
     *
     * @return the value of manager_user.id
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.id
     *
     * @param id the value for manager_user.id
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.username
     *
     * @return the value of manager_user.username
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.username
     *
     * @param username the value for manager_user.username
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.password
     *
     * @return the value of manager_user.password
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.password
     *
     * @param password the value for manager_user.password
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.type
     *
     * @return the value of manager_user.type
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.type
     *
     * @param type the value for manager_user.type
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.status
     *
     * @return the value of manager_user.status
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.status
     *
     * @param status the value for manager_user.status
     *
     * @mbggenerated Sat Dec 12 21:32:21 EST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}