package com.whoops.po;

public class School extends BasePo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.id
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.name_en
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.name_cn
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    private String nameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.name_abbr
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    private String nameAbbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.country
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.latitude
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.longitude
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    private Float longitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.id
     *
     * @return the value of school.id
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.id
     *
     * @param id the value for school.id
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.name_en
     *
     * @return the value of school.name_en
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.name_en
     *
     * @param nameEn the value for school.name_en
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.name_cn
     *
     * @return the value of school.name_cn
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public String getNameCn() {
        return nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.name_cn
     *
     * @param nameCn the value for school.name_cn
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public void setNameCn(String nameCn) {
        this.nameCn = nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.name_abbr
     *
     * @return the value of school.name_abbr
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public String getNameAbbr() {
        return nameAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.name_abbr
     *
     * @param nameAbbr the value for school.name_abbr
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public void setNameAbbr(String nameAbbr) {
        this.nameAbbr = nameAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.country
     *
     * @return the value of school.country
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.country
     *
     * @param country the value for school.country
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.latitude
     *
     * @return the value of school.latitude
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.latitude
     *
     * @param latitude the value for school.latitude
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.longitude
     *
     * @return the value of school.longitude
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.longitude
     *
     * @param longitude the value for school.longitude
     *
     * @mbggenerated Tue Mar 31 19:27:19 EDT 2015
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }
}