package com.whoops.po;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.post_id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.like_num
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    private Integer likeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.dislike_num
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    private Integer dislikeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.uid
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_date
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.post_id
     *
     * @return the value of comment.post_id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.post_id
     *
     * @param postId the value for comment.post_id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.like_num
     *
     * @return the value of comment.like_num
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.like_num
     *
     * @param likeNum the value for comment.like_num
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.dislike_num
     *
     * @return the value of comment.dislike_num
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public Integer getDislikeNum() {
        return dislikeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.dislike_num
     *
     * @param dislikeNum the value for comment.dislike_num
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public void setDislikeNum(Integer dislikeNum) {
        this.dislikeNum = dislikeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.uid
     *
     * @return the value of comment.uid
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.uid
     *
     * @param uid the value for comment.uid
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_date
     *
     * @return the value of comment.create_date
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_date
     *
     * @param createDate the value for comment.create_date
     *
     * @mbggenerated Fri Mar 11 16:16:22 EST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}