package com.whoops.po;

import java.util.Date;

public class LikePost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_post.id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_post.uid
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_post.post_id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_post.type
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_post.create_date
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_post.id
     *
     * @return the value of like_post.id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_post.id
     *
     * @param id the value for like_post.id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_post.uid
     *
     * @return the value of like_post.uid
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_post.uid
     *
     * @param uid the value for like_post.uid
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_post.post_id
     *
     * @return the value of like_post.post_id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_post.post_id
     *
     * @param postId the value for like_post.post_id
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_post.type
     *
     * @return the value of like_post.type
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_post.type
     *
     * @param type the value for like_post.type
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_post.create_date
     *
     * @return the value of like_post.create_date
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_post.create_date
     *
     * @param createDate the value for like_post.create_date
     *
     * @mbggenerated Wed Apr 15 16:56:51 EDT 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}