package com.whoops.po;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.like_num
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Integer likeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.dislike_num
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Integer dislikeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.image
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.longitude
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.latitude
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.school_id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.nick_name
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.comment_count
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.uid
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.activity_id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.status
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.create_date
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.like_num
     *
     * @return the value of post.like_num
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.like_num
     *
     * @param likeNum the value for post.like_num
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.dislike_num
     *
     * @return the value of post.dislike_num
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Integer getDislikeNum() {
        return dislikeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.dislike_num
     *
     * @param dislikeNum the value for post.dislike_num
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setDislikeNum(Integer dislikeNum) {
        this.dislikeNum = dislikeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.image
     *
     * @return the value of post.image
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.image
     *
     * @param image the value for post.image
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.longitude
     *
     * @return the value of post.longitude
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.longitude
     *
     * @param longitude the value for post.longitude
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.latitude
     *
     * @return the value of post.latitude
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.latitude
     *
     * @param latitude the value for post.latitude
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.school_id
     *
     * @return the value of post.school_id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.school_id
     *
     * @param schoolId the value for post.school_id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.nick_name
     *
     * @return the value of post.nick_name
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.nick_name
     *
     * @param nickName the value for post.nick_name
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.comment_count
     *
     * @return the value of post.comment_count
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.comment_count
     *
     * @param commentCount the value for post.comment_count
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.uid
     *
     * @return the value of post.uid
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.uid
     *
     * @param uid the value for post.uid
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.activity_id
     *
     * @return the value of post.activity_id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.activity_id
     *
     * @param activityId the value for post.activity_id
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.status
     *
     * @return the value of post.status
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.status
     *
     * @param status the value for post.status
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.create_date
     *
     * @return the value of post.create_date
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.create_date
     *
     * @param createDate the value for post.create_date
     *
     * @mbggenerated Mon Feb 08 12:42:56 EST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}